import org.jetbrains.kotlin.kapt3.base.Kapt
import org.jetbrains.kotlin.kapt3.base.Kapt.kapt

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"

    // Apply the application plugin to add support for building a CLI application.
    application
    kotlin("kapt") version "1.3.41"
}

repositories {
    mavenCentral()
    jcenter()
    maven(url = "https://jitpack.io")
}

dependencies {

    implementation("org.hexworks.zircon:zircon.core-jvm:2018.12.25-XMAS")
    implementation("org.hexworks.zircon:zircon.jvm.swing:2018.12.25-XMAS")

    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.slf4j:slf4j-simple:1.7.26")
    implementation("io.github.microutils:kotlin-logging:1.7.6")

    implementation("io.arrow-kt:arrow-core:0.10.3")
    implementation("io.arrow-kt:arrow-syntax:0.10.3")
    kapt ("io.arrow-kt:arrow-meta:0.10.3")

    testImplementation("org.amshove.kluent:kluent:1.56")
    testImplementation("org.spekframework.spek2:spek-dsl-jvm:2.0.8")
    testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:2.0.8")
    testImplementation("org.junit.jupiter:junit-jupiter:5.5.2")
}

application {
    // Define the main class for the application.
    mainClassName = "com.conpinion.gameoflife.GameUiKt"
}

tasks {
    test {
        useJUnitPlatform {
            includeEngines("spek2", "junit-jupiter")
        }
        testLogging {
            events("passed", "skipped", "failed")
        }
    }
}
