/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.conpinion.gameoflife

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test


class GameTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = Game(listOf(
                Cell(0,0, true)
        ))
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
